site_name: pxtextmining
site_url: https://cdu-data-science-team.github.io/pxtextmining/
theme: readthedocs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: true
            show_root_toc_entry: false
            show_root_full_path: false
            show_source: false
            show_if_no_docstring: true
            heading_level: 4
