[tool.poetry]
name = "pxtextmining"
version = "0.4.0"
description = "Text classification of patient experience feedback."
authors = ['CDU Data Science <cdudatascience@nottshc.nhs.uk>',
'Andreas D Soteriades <andreas.soteriades@nottshc.nhs.uk>',
'YiWen Hon <yiwen.hon@nottshc.nhs.uk>']
readme = "README.md"
license = "MIT"
repository = "https://github.com/CDU-data-science-team/pxtextmining"
documentation = "https://cdu-data-science-team.github.io/pxtextmining"

[tool.poetry.dependencies]
python = ">=3.8,<3.10"
emojis = "^0.6.0"
spacy = "2.3.5"
imbalanced-learn = "0.7.0"
joblib = "^1.2.0"
matplotlib = "3.3.2"
mysql-connector-python = "8.0.23"
nltk = "3.6.6"
numpy = ">=1.22"
pandas = "1.2.3"
pyparsing = "2.4.7"
python-dateutil = ">=2.8.2"
pytz = "2021.1"
regex = "2021.8.3"
requests = "2.25.1"
scikit-learn = "0.23.2"
scipy = "1.6.3"
seaborn = "0.11.0"
six = "1.16.0"
SQLAlchemy = "1.3.23"
srsly = "1.0.5"
textblob = "0.15.3"
thinc = "7.4.5"
threadpoolctl = "2.1.0"
tqdm = "4.61.0"
urllib3 = "1.26.5"
vaderSentiment = "3.3.2"
wasabi = "0.8.2"
tensorflow = "^2.11.0"
uvicorn = "^0.20.0"
fastapi = "^0.88.0"


[tool.poetry.group.dev.dependencies]
deptry = "^0.7.0"



[tool.poetry.group.docs.dependencies]
mkdocs = "^1.4.2"
mkdocstrings-python = "^0.8.2"
mkdocstrings = "^0.19.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
