name: Check execution

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches:
      - development

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install .
        python -m spacy download en_core_web_sm
        python -m spacy download en_core_web_lg
    - name: Test execution files
      run: |
        python execution/execution_label.py
        python execution/execution_predict.py
